<a href="https://colab.research.google.com/github/rgush/TF_LEARN_PUB/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# In this notebook, we're going to cover some of the most fundamental concepts of tensors usng TensorFlow

# In this notebook, we're going to cover some of the most fundamental concepts of tensors usng TensorFlow
More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
*Manipulating tensors
Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercies to try for yourself

## Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf

In [2]:
print(tf.__version__)

2.7.0


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands fro number of dimensions)
scalar.ndim


0

In [5]:
# Create a vector
vector = tf.constant([10, 20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [6]:
# Check the dimension of our vector
vector.ndim

1

In [7]:
# Create a matris
matrix = tf.constant([[1, 0, -1, 7], [3, 2, 1, 7], [0, 4, 6, 7]])
matrix

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  0, -1,  7],
       [ 3,  2,  1,  7],
       [ 0,  4,  6,  7]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix
matrix_2 = tf.constant([[1, 0, -1, 7], [3, 2, 1, 7], [0, 4, 6, 7]], dtype=tf.float16)
matrix_2

<tf.Tensor: shape=(3, 4), dtype=float16, numpy=
array([[ 1.,  0., -1.,  7.],
       [ 3.,  2.,  1.,  7.],
       [ 0.,  4.,  6.,  7.]], dtype=float16)>

In [10]:
matrix_2.ndim

2

In [11]:
# Let's creat a tensor
tensor = tf.constant( [ [ [1, 2, 3],
                        [4, 5, 6] ],
                      [ [7, 8, 9],
                        [10, 11, 12] ],
                      [[13, 14, 15],
                       [16, 17, 18] ] ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

### Creating tensors with tf.Variable

In [13]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

# Let's try to change one of the elements in our changeable tensor

In [14]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
unchangeable_tensor[0].assign(20)

AttributeError: ignored

### Creating random tensors
Random tensors are tensors with some abitrary size which contain random numbers

In [16]:
# Create two random (but the same) tensors
tf.random.set_seed(10)
random_1 = tf.random.uniform((2, 2), seed=15)
tf.random.set_seed(10)
random_2 = tf.random.uniform((2, 2), seed=15)
random_1, random_2

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.49807692, 0.97861147],
        [0.38950872, 0.41255903]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.49807692, 0.97861147],
        [0.38950872, 0.41255903]], dtype=float32)>)

In [17]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [18]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [19]:
# Check if tensors are equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [20]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order does not effect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [23]:
# Shuffle our tensor
tf.random.set_seed(42)
shuffled = tf.random.shuffle(value=not_shuffled, seed=15)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [24]:
array_var = tf.Variable([1, 2, 3, 4, 5, 6])
array_var

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [25]:
tf.random.shuffle(array_var)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 6, 4, 3, 5, 1], dtype=int32)>

In [26]:
tf.random.shuffle(array_var, seed=20)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([4, 6, 2, 5, 1, 3], dtype=int32)>

In [28]:
tf.random.set_seed(254)
tf.random.shuffle(array_var)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([4, 5, 6, 2, 3, 1], dtype=int32)>

### Other ways to make tensors

In [29]:
# Create a tensor of all ones
tf.ones([2, 3], tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [30]:
# Create a tensor of all zeros
tf.zeros([2, 5], tf.int32)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [33]:
# Turn NumPy array into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [34]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [43]:
a_var = tf.Variable(numpy_A)
B = tf.constant(numpy_A, shape=(6, 4))
B, B.ndim, a_var

(<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]], dtype=int32)>,
 2,
 <tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [41]:
a_var[0].assign(10)
a_var

<tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

### Getting information from tensors