<a href="https://colab.research.google.com/github/rgush/TF_LEARN_PUB/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# In this notebook, we're going to cover some of the most fundamental concepts of tensors usng TensorFlow

# In this notebook, we're going to cover some of the most fundamental concepts of tensors usng TensorFlow
More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
*Manipulating tensors
Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercies to try for yourself

## Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf

In [2]:
print(tf.__version__)

2.7.0


In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the number of dimensions of a tensor (ndim stands fro number of dimensions)
scalar.ndim


0

In [6]:
# Create a vector
vector = tf.constant([10, 20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [7]:
# Check the dimension of our vector
vector.ndim

1

In [8]:
# Create a matris
matrix = tf.constant([[1, 0, -1, 7], [3, 2, 1, 7], [0, 4, 6, 7]])
matrix

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  0, -1,  7],
       [ 3,  2,  1,  7],
       [ 0,  4,  6,  7]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# Create another matrix
matrix_2 = tf.constant([[1, 0, -1, 7], [3, 2, 1, 7], [0, 4, 6, 7]], dtype=tf.float16)
matrix_2

<tf.Tensor: shape=(3, 4), dtype=float16, numpy=
array([[ 1.,  0., -1.,  7.],
       [ 3.,  2.,  1.,  7.],
       [ 0.,  4.,  6.,  7.]], dtype=float16)>

In [11]:
matrix_2.ndim

2

In [12]:
# Let's creat a tensor
tensor = tf.constant( [ [ [1, 2, 3],
                        [4, 5, 6] ],
                      [ [7, 8, 9],
                        [10, 11, 12] ],
                      [[13, 14, 15],
                       [16, 17, 18] ] ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

### Creating tensors with tf.Variable

In [14]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

# Let's try to change one of the elements in our changeable tensor

In [15]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
unchangeable_tensor[0].assign(20)

AttributeError: ignored

### Creating random tensors
Random tensors are tensors with some abitrary size which contain random numbers